global: {}
mq-spring-app:
  replicaCount: 1

argocd-hook-job:
  name: promote-dev-stage-trigger
  namespace: dev
  hook:
    enabled: true
    hooktype: PostSync
  hookdeletepolicy:
    enabled: false
    hookdeletepolicytype: HookSucceeded
  serviceaccount: pipeline-hook-argocd-hook-job
  roleaccess:
    - verbs:
        - '*'
      apiGroups:
        - 'tekton.dev'
      resources:
        - pipelines
        - tasks
  init:
    enabled: false
  container:
    image: "quay.io/rhcanada/tkn-cli"
    tag: "latest"
    command: "tkn"
    args:
      - -n 
      - ci
      - pipeline
      - start
      - ibm-mq-promote-dev-stage
      - --param
      - git-url="https://github.com/cntk-acme-gitops-demo/mq-spring-app.git"
    