apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-ace-rest-prod-1
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: ace/environments/overlays/prod
    repoURL: https://github.com/cntk-acme-gitops-demo/multi-tenancy-gitops-apps
    targetRevision: ocp47-2021-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
