apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgCj4fMc6chfbYxmbFuH1NRn3mHqfR9xCO/mTo5cLFAF0OSKqvUNADjU//tJ0JabEMV36VvScbkpFEPL8ddYm3yePnWwuGqD1kaYU5FEZdlAWGfRVvRC6yKpDpJngbGSKbqfgjAJtfyUWAKSUvHMPZAyyCZ887g1Z36PvKqJwTgrWjW90RKg031EFES0B/9TIE14FkpkBYYcY2omtKC/ggT42+DzNIywmO+z6Ej9o3RVe+8K2FEQNUAi6uRI12D/RvVbVZxSqCaWRqzC6OlDDA3R76T39/5KgpwCWd2vNQIsBDs3ONyHZQ/Bxg4239nD+r8/mm1+ImdgU2MmqFaT4RUa7agsBQRAiv+XkKyzSLYsl6wRYdM1UqK5MMEdMlfooIocXgwHRDHTwyByTacF9eIuXkLCsYPCd0EzDTtmjwkxKxF4w0/vKzqXkVaAlbjC1yDeGGd+GoJynW5kvHbM+7k3rBo7tsk+2tDN7StUrIDrVHMDFbZtHdt+k/Hah0Pjt3CGS+1kB8W1A+lhTQg+eoKXP3PDbjAViglkSVHiBn1fvv1GlB16+ETDO8FQxEg/M9+wFlQWFZ6jtdxykgZKMwCzvtNLTpTSwbBSrAFicYG3xi1gdkDAhd+/SA4I9XHiIwwoK6M4PkcxgU0vfQkESVriOabjxlKQErXd6UG8fADJtb4w6X68pWqLIMhLwca2nB/jcl1kxvbxT4AqV+X2+469brnW488w8f1zWdUBb61Jj92tsQlgsQ==
    ARTIFACTORY_PASSWORD: AgALH8UNxq9hsz7LFGvUk/PZ34h82TR9d0waLTxjTsbnNCMzHN5bNxqHnD0F+xjCOP9TeGZDyTt23niGjBfwqIlabSYMmim7Xfdj22y1+hF/Hh/M32S3H4p3L73bCWlImDn7ORBlmxWNhvrJusOeRjPy3beYCdYZuhD3ihdw9yW5VT6F+CCtYojhmPOlya0B+3SwKgkuMVN4APi+sWZMg6WFMsIGMd1Lnm3Cf8yeqBkqhC9ACSStsBCIaAZT0hKaNGWBkTIsJYMZQGNE1qA9k8WciLu0+ZueLlUNNAdmAPVYbo6XZw6qor3woaeAQTYBXnHXP8EmPB+kwkZAd1ckzCM4SJgFk2jL1JlF+CvQPVuuky2geWhYMgTZy66DrOpBka+KHawqlyetlllM6NyEX8F/hfNizSs6vvKJa/S9fovHYt5Catph9SKv7M+0ZWLp4lFQ/KpoBVQh3iil7CpQKh4EBDyMj92vZUr/xTbpS/CWEfOmC0KGmhj+/1nrhCerx2EDvP7EXIhea3DnvgNoI10D6wW5NjJyOSka7YZuHdR97jGyLetj4uiJamjah06X/FMa9ByMobE6arC8lFr/bmnUc1VYPX3s35CotOAAX0Z4hPGtQL3cZcz3uIRLgEQhh42Rft7ErwdVQfldzcBh8Ho2G60Dk8D7V//7GZAyOEcxWgYFokUDogPPPNHCjymMVK2f5PF+ZgrcvZPJvuYW/VDF3tMdmg==
    ARTIFACTORY_URL: AgAdl0s8wlU1Mg5OlqmXLtmGZEgULMTNXthGwD/s9sIhhO1OdN6XBh7JfK5WASpF+JbSYbTTHtctpxuZt5Mb9myHLgUzlonBC67/glT8mGSJWPlWi56EDiw0tq4bssKpRhS9r6nKKJJNV/FXVrYASs2kOi0pxJPqAIODQFB9J0QJg2ozl11LeywslXGXLQQIdcsBdLn1mN5rk/DFxr1BizRF+tPpIRVFt1Dn7XijuQNMsrZBKomv6O06zxBa2XVze2Lc+FeZyDB/ddY5CsmjYywu3lX0ho9htB9xBnnNm70ztQho5gFsXLcdwMHWHYS3UbZOTsSp+RaqIBA+B2YyQPajXDjrkyYatNeHITzTcYwiK07/6hyEHc9hCqa6kEnnFggj8W8xJlWJZZY5FfN/kKB2yq1U7zrgDmHtd3lynKfLUtjOc6izXZVZQX1rJoFEt6Q93vwh1wCX3Q5qkVh+7p+Dxu1iWW6Uq40UcUgSlt2jvoYt9uGy12WGRW6U+2wyU8E8QPneLn0Yk1Z6OKHUCEmfnAB8HlPC0L9qgdAEPQ6tacENF4s+Qx7e+jkYlskFQksGodO41f4gfk4tduSNQnh6RaDADKkBq1bbxb0G0ZDcPc60kp/Pwiw5hD2uyDBx+SpE1jyDa3N1lJE4LHXTis1P3BAGn/cH2tFKzuvQGNlajKvOQxuFUFuzFMwx6HZ5jEHrj2SNv87KYpj5DoRXLB9E1a5Qx2BuYiJaNORxeqMUyP2TRf0A96bbcA==
    ARTIFACTORY_USER: AgCDRsdKEOeItmrq3h1Vd8NPQVRXYp5e85zz/o4OUR7nE+9q/ejutcnsMNn7lQQba89GVGO3Ep/sJLD/j6hJ24E4fPMp1Y6e9Jb6hCPwk5q34UhNcHUaPZbUNo00GFTACsGL5RDRMhhjjIXvVcmXHpgb1+YQNoepK9jrpFc3w2kaKAEq7xagMgS/eIMJdFWVgINO/fktQ54pisTCnlrnMV+LxsalF20serl+ILOYdMgwMbnFlPTvqWHih5bfNLQtYzwOcCtpQMujCCfbuC+eNZ6tjflrNWN9pfTGZsAxt6mqvLMtwt28CTG9Pueo+1RXcX/iFqgPFsR/DCZ7ck1O3F/B3RgAg5NCw4cpshGv7I1NjACPpBGGs3YiLVCgWE8Y4VCsxmT4llAod9fmqFUYQobwXsKwhmnELe0824GGKV7+FPn/iyV+bBOXjEE4aCOtLo0hCpleeJT5TIPhZvTboy2/EaiRU/E6MmKxIqeDTXvxaBoEGZeEW8i0anKvwuT/qmwbfGRgHKxStbSTYk0A0zubrntrsFLAKhDRaHC7uf+ycdRm1K+G0lSy/LOkKfCnG93SasB/kNSA9lmlg/0TYValNvHTVFHfOuYjzDLUjZjVIiiqcZYy5AFQLT1Lz0SeYZK1aQwVe+cngiNV004plOknGi+r2Sb3DoFLhVluevoftDRyHbwEMDKCbKFs5AI6lb1adWvDfA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:type: {}
        manager: kubectl
        operation: Update
        time: "2021-09-20T03:09:58Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
        manager: unknown
        operation: Update
        time: "2021-09-20T03:11:03Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

