apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgBH9dbjb0ezDleUn+DSOEwwO+62JkazD7UUrMHKOcIJ9l6i4AoWRtQ4YTvhK4tM++e7Y/WyEDgJGUoekF1FWM+gxej6qjN0926DmMgY+nZ3LcjjA4pUbREc2QPNdUfeillMvxanMsCH8uBwScU7Bbtk5pJmEeqkpomDFG/nSq6rDq27xWLglbKIhPUP2qnuu+4/eX4257SMpn5YgXre3+vDt+TxpBJcp3ro/6539F6NHSxFOamCQPAiOMdoGiLL45mXLKVboLWu+mRTJ7gR2Wj9RAGbsuLt+Upr2i9XxaUlRoHztmLY27LY0nBRQ/PyJgvkuld/LMf7Q9maN6W8BbJd2DaNCT6Bv52XHsDlKobcW9XgzvgVU6XAqkHhAXcFJgmFbEQt9ERtnml5v/yIayjJnbfXSNsZ1d8RDBzMuMm+YcOzgNn2qjHz/UNN4Hwg8d2ly94OTR7Tsy9mZN9FalI42eXJQiSOeMzYgL3O6wQMiXN9jFD3SacgFd71G1btlbE/izLV3PVDCkcny0+A7KFocMCEqtJFKUuAOnOpSM9V76H+EA+rYsJ6//V9KgsJ0aeQNgBKYHZeUuJYGkpqdxCoMiht5UWwNR0u0rKBJk8753GmWyWNQ8W0Bod/KM92D8/0sT3rcIbc3cIp3u+Hah3EMHx2OLQzrAZZkD7wzyb/Xv6nHvZFW2aJbPk1l0ZFzYua4Wri4CV3J4n+ISEi++ggltCnJb1fsdSv8A9yF+CJ+OSKiK73aBJ7
    username: AgANYYl8ebURYWmOQz0RH8lGbh9+nujSBzSJKCs8YCI+tz6dmC8YDlF/tUA0AFBz+6RVBXjGzVQzCrIwxuGLcHvD1uOnGvLox4+HFMzQYs1oIL17F22OB1++ul6AZJ98amZ0v+L89Ztv6i1w0vR5hEkP/NbTD4fJ/grOfbsmsxZx4eMVjl7Jm4cpBWeI4TNZYDV5GL8yJN3CbEWSH28chqR6Dswqi66i29RNRWnTg7ZR7LUhvtmo39HfC5QxAHHmH5+uTROz1VMDgoy/0E6Od650ghDTIB7NrdfVPuDprmPl3ZO4fizyQniMq5o3+bXP0vVtZydu8J2ItOOqGrZ8w2uCb7ppbw4XSO00pyhl8TdBDTj1kx+og8eTPMu0EPoqow22C0q1kwBAXhmtgytcjuGaiq7Legf96Ytqn8C/Ww7Qf6aARm4x8N7obvFroUce6hmwseq+Cl6RdQUWnvwFvFPXyoPTk7monaXHrBIOmcmLZ75rAol/XD/lupUTqG95mRqWlF/t2dXSbnQAh3cZ/QJfjxcCzgGIfjeuSU8vi5zeleuZmmVBOMv1uCzKsOGeVf/WVWtwQWkhNpzenfKoMTkYbu3b0R0ZKb3XZPKWN3lbxsL+cAyHaEMZdZ/x4GG4La/+55ce04Hoj3R7vE3lJFUsicx7P2grR45xnCHY/iGMb+Ypkp5eyHF5G0VX9VvvTRpZaBzUikuI
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

