apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgAbsqx7htUOkna1P/A3o/E+2J+Amon2FCEQMFGEgSRDu9SL7Sgaq8SQhXKoIVmTyFBVI1QrtfSFKXxkudqkjbBNoxUwbHLAwD5XMhVih7j+TAo1vhlyieWQehwfZZmyc4k9uk32WPFuWzt5+209pKFSancUjBNeAicL5wNqKw+/GXj8VmA1UyW3IlntWj6hAFQ42PQBPi2+lxj+1rwPMqUX9/UggJfjv9EsQ+mROJ2PdVBJiETl8rB+1t4UO04sTEpEddQKjveW2iHoPxgfdxHynJspf/NEIECbuIN+pRnWtIf8RmCbgm3VHyHPlpzay6cirqT/4dG7n7ABKm5vS8z1lQzPQBoeC0jkG/169hcGEcQPVFxOjz5T1gXyTeYZgJ6vTd4o9CCfYVlQw8s7KEL1AfAjxrrRh+8tgMcu710mv2+EsHcDdpwkQmBaRAMely08om1neMhn+NgEgapVP0EfJUbbV50kNdnhB4/Q/Ny4xn940vZ3h+2LQWM++Le4hsIn2wbKjHET4fIcvk6Q7RWqniaEPcU6DG3iAmdfsLbQsbJwxShC4QzEqElE7LcKYLXwHNuePMbnZj000PXcVRAvb7C3G8borAqcJOKshUmlmeLWoIbUGzXjQH5AUWjhS8W1j4PQpQVRayL3U/IzHyogfzXmfTx4skCIb8XrdMd7br3fcTQkvkPnZ+somCnGyKb7ZWVGSi+ONhfTpfrDKgNuZgSoPMa4L7+qk36M9b8zXoFGXDdyyq9c
    username: AgCBFVbtXYLTQ1KmHEpThLaF3txjlKcyfut1tcsyicM0WRigTxCWBnnLV0nASRZK55Ix9grhp2wUYL1Z6BzWrrkslBN2RCzx5y+xn8uh9jew/QL1JLrvNy3taWkhZdvipgum9PLk8J/hv1qecU8L3NjI/AcFg4nN+UTVfsuwPQiNPe7szndSANnyZUcGvzlp5FBjdLRwvrf/D4Gde+HstUJxlKaOVhq5Ff7HWzHCAegQSx1RnVMkqxDeVEkte7DvnFz4m2M+nua13237l0qTQZnqoP247HP2fxHEwGa0wYFN3mMfy30KfJ81V19/K5OAw4aKoLc272eBgBLkPPy/LGHUiEa7HQvYbnbQjdn6jviUr2qr8KGDjv2ANUxQHh4xPqVtev5YawFwQKrAEh4IW+C9DZyuTGhouPbV/APA7Q/HY20SAEAesu9MjlMZmAOIb7RFm5w1v9GsgmutxfGisxm+Nuw5IjKLYstGqqleGpxsWifQZM32e6FoWJ5ruL0UfjVdopZp43gPRPxzOPNsIyTtJYxKtLGwJu/FtSlqy2byGIkt5AatdXcEWC0sOuVt1r7rv40vkDNuRuyEYJDR6oXDnfcpoC78VXBErgsfL+TlxgLQmbv0kEwQ/x7VPEs+1x7OFhaizWU14uIXO3TC9DLvVH0nyku+0SJr8nPt+Yfxe3bt1NHW0TC0HbFepP4QTMPyLxbf4NBf
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

